### ISSUE TITLE
Qt 5.15: не удаётся найти Java-класс при регистрации JNI

### ISSUE THREAD

**Issue by Kerminator1973** [Kerminator1973/Qt5JNI2Android#1]
Приложение падает (SIG33) при попытке выполнения следующего кода:

```cpp
QAndroidJniObject javaClass = QAndroidJniObject(HELPER_CLASS_PATH);
QAndroidJniEnvironment env;
jclass objectClass = env->GetObjectClass(javaClass.object<jobject>());
```

Текст сообщения из логов Android:

```
W System.err: java.lang.ClassNotFoundException: Didn't find class "ru.kerminator.qt5research.AndroidHelper" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /system/vendor/lib]]
W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
W System.err: 	at org.qtproject.qt5.android.QtNative.startQtApplication(Native Method)
W System.err: 	at org.qtproject.qt5.android.QtNative$7.run(QtNative.java:499)
W System.err: 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
W System.err: 	at java.lang.Thread.run(Thread.java:764)
F zygote  : java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: java_object == null
F zygote  : java_vm_ext.cc:534]     in call to GetObjectClass
```

**Comment by Kerminator1973** [comment]
Похоже на мой косяк pro-файле - добавлял ANDROID_PACKAGE_SOURCE_DIR только при сборке под x86:

```
contains(ANDROID_TARGET_ARCH,x86) {
    ANDROID_PACKAGE_SOURCE_DIR = \
        $$PWD/android
}
```

**Comment by Kerminator1973** [comment]
После того, как активировал сборку под ARM сборка развалилась:

```
adb: failed to install D:/Sources/build-Qt5AndroidJNI-Android_armeabi_v7a_arm64_v8a_x86_x86_64_Clang_Qt_5_15_0_for_Android-Debug/android-build//build/outputs/apk/debug/android-build-debug.apk: Failure [INSTALL_FAILED_USER_RESTRICTED: Install canceled by user]
...
Installing to device failed!
14:21:41: Процесс «C:\Qt\5.15.0\android\bin\androiddeployqt.exe» завершился с кодом 16.
```

**Comment by Kerminator1973** [comment]
Приложение не запускается теперь и на эмуляторах x86:

```
Do you need "set solib-search-path" or "set sysroot"?Could not load shared library symbols for /system/lib/vndk-sp/android.hardware.graphics.mapper@2.0.so.
Do you need "set solib-search-path" or "set sysroot"?I System.out: debugger has settled (2524)
W ResourceType: Invalid package identifier when getting bag for resource number 0x00000000
E Qt      : Can't create main activity
E Qt      : android.content.res.Resources$NotFoundException: String array resource ID #0x0
E Qt      : 	at android.content.res.Resources.getStringArray(Resources.java:576)
E Qt      : 	at org.qtproject.qt5.android.bindings.QtLoader.startApp(QtLoader.java:423)
```

**Comment by Kerminator1973** [comment]
Проблема не решена. Вероятно нужно будет снова попробовать создать приложение с "чистого листа".

**Comment by Kerminator1973** [comment]
В моём build.gradle не было вот такой строки:

```
android {

    compileSdkVersion androidCompileSdkVersion.toInteger()

    buildToolsVersion androidBuildToolsVersion

    defaultConfig {
        applicationId "ru.kerminator.qt5research"
        multiDexEnabled true
    }
```

**Comment by Kerminator1973** [comment]
Статья про имеющуюся в моём приложении ошибку:
https://stackoverflow.com/questions/61097966/qt-on-android-runtime-error-invalid-package-identifier-when-getting-bag-for-res

Если принять во внимание рекомендации, то изменилась структура "AndroidManifest.xml". До Qt 5.13 она была как раньше, а в 5.14 и выше произошли серьёзные изменения в коде.
